load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "logger",
    srcs = glob(["*.cpp"]),
    hdrs = glob(["*.h"]),
    includes = ["Fast-DDS/include"],
    visibility = ["//visibility:public"],
)
